/* 
 * File:   PLATFORM_CONFIGRATION.h
 * Author: ENG.RAGAB
 *
 * Created on 05 ?????, 2018, 02:43 ?
 */

#ifndef PLATFORM_CONFIGRATION_H
#define	PLATFORM_CONFIGRATION_H

#include <p24FJ256GA705.h>

#define _XTAL_FREQ 8000000UL
/*THIS SECTION FOR I2C */
//LOOK AT DATASHEET TABLE 18-1: I2Cx CLOCK RATES
/*
 IF SOURCE_CLOCK(_XTAL_FREQ = 16MHZ) FOR HIGH RATE ..CHOOSE = 0X08 OR 0X02
 IF SOURCE_CLOCK(_XTAL_FREQ = 8MHZ) FOR HIGH RATE ..CHOOSE = 0X03
 */
#define CLOCK_I2C 0X08

/*LCD CONFIGRATION*/
/* IT CONSIST OF MSB(0 1 0 0 A2 A1 A0 R/W)   (A2 A1 A0) IS PINS IN LCM1600 YOU CHOOSE TO MAKE IT HIGH OR LOW 
 I MAKE THREE  GROUND SO ADRESS WILL BE 0X40  */

#define ADDRESS_OF_LCD 0x40


/*keypad setting*/
/*WE HERE USE PORTB:
 - ROW RB0 TO RB3
 - COL RB4 TO RB4 
 */
#define CHECK_ON_ZERO
#define KEYPAD_DDR TRISB
#define KEYPAD_CTRL PORTB
#define KEYPAD_PIN  PORTB
#define COL 4
#define ROW 4

#endif	/* PLATFORM_CONFIGRATION_H */

